name: Metrics
on:
  schedule:
    - cron: "27 3 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: juliandeveloper05
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_details: percentage, bytes-size
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
