name: Metrics
on:
  schedule:
    - cron: "27 3 * * *"   # diario (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token personal (ya está como secret)
          token: ${{ secrets.METRICS_TOKEN }}
          # Forzamos que también se use tu PAT para commitear el metrics.svg
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # Config mínima y estable
          user: juliandeveloper05
          template: classic
          base: header, activity, repositories
          config_timezone: America/Argentina/Buenos_Aires

          # Plugins seguros
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_details: percentage, bytes-size
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
